### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by zraffer** [konn/vscode-agda-interactive#3]
as far as the atom plugin is not working now, this page seems to be the only plugin for the alternative editor.
but how to run it? why it is not published with other plugins? 

is it working plugin?

**Comment by konn** [comment]
This is my personal project (not an official project of Agda development team) and in a very early stage of development. Hence, its functionality really tends to change, and you cannot expect it to behave as an alternative as Emacs Agda mode.

**Comment by konn** [comment]
Its functionality is currently limited to a small portion of exact syntax colouring.
Because the usage of Agda in my everyday work is really small, the current development speed is quite low. So you cannot expect this repo to get matured in the near future.
But, since it's an open-source project, you can feel free to send pull-request to this repo!

**Comment by zraffer** [comment]
Thank you!
